export const dto = {
  events: [
    {
      id: 1,
      input: [],
      output: [1, 2, 3, 4],
      type: 1,
    },
    {
      id: 2,
      input: [1],
      output: [28],
      type: 2,
    },
    {
      id: 3,
      input: [2],
      output: [12],
      type: 2,
    },
    {
      id: 4,
      input: [4],
      output: [5, 6, 7, 8],
      type: 2,
    },
    {
      id: 5,
      input: [3],
      output: [9],
      type: 2,
    },
    {
      id: 6,
      input: [9],
      output: [10],
      type: 2,
    },
    {
      id: 7,
      input: [5],
      output: [11],
      type: 2,
    },
    {
      id: 8,
      input: [6],
      output: [15],
      type: 2,
    },
    {
      id: 9,
      input: [7],
      output: [13],
      type: 2,
    },
    {
      id: 10,
      input: [8],
      output: [14],
      type: 2,
    },
    {
      id: 11,
      input: [10],
      output: [17],
      type: 2,
    },
    {
      id: 12,
      input: [11, 17],
      output: [18],
      type: 2,
    },
    {
      id: 13,
      input: [13],
      output: [16],
      type: 2,
    },
    {
      id: 14,
      input: [14],
      output: [19],
      type: 2,
    },
    {
      id: 15,
      input: [12],
      output: [20],
      type: 2,
    },
    {
      id: 16,
      input: [15],
      output: [26],
      type: 2,
    },
    {
      id: 17,
      input: [18, 20],
      output: [21],
      type: 2,
    },
    {
      id: 18,
      input: [16],
      output: [25],
      type: 2,
    },
    {
      id: 19,
      input: [28],
      output: [29],
      type: 2,
    },
    {
      id: 20,
      input: [26],
      output: [27],
      type: 2,
    },
    {
      id: 21,
      input: [19],
      output: [22],
      type: 2,
    },
    {
      id: 22,
      input: [21, 27],
      output: [31],
      type: 2,
    },
    {
      id: 23,
      input: [22, 25],
      output: [23],
      type: 2,
    },
    {
      id: 24,
      input: [29],
      output: [30],
      type: 2,
    },
    {
      id: 25,
      input: [23, 31],
      output: [24],
      type: 2,
    },
    {
      id: 26,
      input: [24, 30],
      output: [],
      type: 3,
    },
  ],
  id: 101,
  tasks: [
    {
      duration: "3m",
      end: 2,
      id: 1,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 1",
      real: null,
      start: 1,
      type: 1,
    },
    {
      duration: "2m",
      end: 3,
      id: 2,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 2",
      real: null,
      start: 1,
      type: 1,
    },
    {
      duration: "3m",
      end: 5,
      id: 3,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 3",
      real: null,
      start: 1,
      type: 1,
    },
    {
      duration: "4m",
      end: 4,
      id: 4,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 4",
      real: null,
      start: 1,
      type: 1,
    },
    {
      duration: "2m",
      end: 7,
      id: 5,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 5",
      real: null,
      start: 4,
      type: 1,
    },
    {
      duration: "2m",
      end: 8,
      id: 6,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 6",
      real: null,
      start: 4,
      type: 1,
    },
    {
      duration: "3m",
      end: 9,
      id: 7,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 7",
      real: null,
      start: 4,
      type: 1,
    },
    {
      duration: "5m",
      end: 10,
      id: 8,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 8",
      real: null,
      start: 4,
      type: 1,
    },
    {
      duration: "4m",
      end: 6,
      id: 9,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 9",
      real: null,
      start: 5,
      type: 1,
    },
    {
      duration: "12m",
      end: 11,
      id: 10,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 10",
      real: null,
      start: 6,
      type: 1,
    },
    {
      duration: "2m",
      end: 12,
      id: 11,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 11",
      real: null,
      start: 7,
      type: 1,
    },
    {
      duration: "4m",
      end: 15,
      id: 12,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 12",
      real: null,
      start: 3,
      type: 1,
    },
    {
      duration: "4m",
      end: 13,
      id: 13,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 13",
      real: null,
      start: 9,
      type: 1,
    },
    {
      duration: "12m",
      end: 14,
      id: 14,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 14",
      real: null,
      start: 10,
      type: 1,
    },
    {
      duration: "6m",
      end: 16,
      id: 15,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 15",
      real: null,
      start: 8,
      type: 1,
    },
    {
      duration: "16m",
      end: 18,
      id: 16,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 16",
      real: null,
      start: 13,
      type: 1,
    },
    {
      duration: "2m",
      end: 12,
      id: 17,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 17",
      real: null,
      start: 11,
      type: 1,
    },
    {
      duration: "3m",
      end: 17,
      id: 18,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 18",
      real: null,
      start: 12,
      type: 1,
    },
    {
      duration: "14m",
      end: 21,
      id: 19,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 19",
      real: null,
      start: 14,
      type: 1,
    },
    {
      duration: "3m",
      end: 17,
      id: 20,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 20",
      real: null,
      start: 15,
      type: 1,
    },
    {
      duration: "2m",
      end: 22,
      id: 21,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 21",
      real: null,
      start: 17,
      type: 1,
    },
    {
      duration: "12m",
      end: 23,
      id: 22,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 22",
      real: null,
      start: 21,
      type: 1,
    },
    {
      duration: "2m",
      end: 25,
      id: 23,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 23",
      real: null,
      start: 23,
      type: 1,
    },
    {
      duration: "1m",
      end: 26,
      id: 24,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 24",
      real: null,
      start: 25,
      type: 1,
    },
    {
      duration: "12m",
      end: 23,
      id: 25,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 25",
      real: null,
      start: 18,
      type: 1,
    },
    {
      duration: "12m",
      end: 20,
      id: 26,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 26",
      real: null,
      start: 16,
      type: 1,
    },
    {
      duration: "2m",
      end: 22,
      id: 27,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 27",
      real: null,
      start: 20,
      type: 1,
    },
    {
      duration: "4m",
      end: 19,
      id: 28,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 28",
      real: null,
      start: 2,
      type: 1,
    },
    {
      duration: "6m",
      end: 24,
      id: 29,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 29",
      real: null,
      start: 19,
      type: 1,
    },
    {
      duration: "2m",
      end: 26,
      id: 30,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 30",
      real: null,
      start: 24,
      type: 1,
    },
    {
      duration: "2m",
      end: 25,
      id: 31,
      isConnected: true,
      max: null,
      min: null,
      name: "Работа 31",
      real: null,
      start: 22,
      type: 1,
    },
  ],
  title: "Учебный сетевой график",
};
